import { h } from '../../lib/core/dom.ts';
import type { CatalogEntry } from '../types.ts';

import { InitiativeTrack } from '../../lib/components/InitiativeTrack.ts';
import { BattleGrid } from '../../lib/components/BattleGrid.ts';
import { Reticle } from '../../lib/components/Reticle.ts';
import { KillFeed } from '../../lib/components/KillFeed.ts';
import { PhaseTracker } from '../../lib/components/PhaseTracker.ts';

/** A dark box the size of a HUD, for components that overlay a scene. */
const scene = (height: string, ...kids: Node[]) =>
  h('div', {
    class: 'demo-scene',
    style: {
      position: 'relative',
      width: '100%',
      height,
      borderRadius: '8px',
      overflow: 'hidden',
      background:
        'radial-gradient(ellipse at 50% 30%, rgba(120,90,60,.35), transparent 60%), #16130f',
    },
  }, ...kids);

export const SKIRMISH: CatalogEntry[] = [
  {
    id: 'InitiativeTrack',
    name: 'InitiativeTrack',
    group: 'combat',
    blurb: 'The turn queue: who acts now, who is next, and how many turns until yours comes round.',
    description:
      '`TurnMeter` shows speed bars filling; this shows the resulting order, which is what a player actually plans against. The queue is generated by cycling the roster until it has enough entries, so a lookahead longer than the party wraps into the next round and shows the break — the moment planning really turns on. A stunned combatant keeps its slot and is marked as skipping rather than vanishing, because a queue that silently drops a unit is a queue nobody can trust.',
    tags: ['initiative', 'turn order', 'queue', 'turns', 'combat', 'lookahead', 'round', 'speed', 'tactics', 'jrpg'],
    related: ['TurnMeter', 'PhaseTracker', 'BattleGrid', 'HUD'],
    demos: [
      {
        title: 'Eight turns ahead',
        note: 'The queue wraps into the next round and marks the break. The stunned unit keeps its place.',
        build: () => {
          const track = new InitiativeTrack({
            title: 'Turn order',
            round: 3,
            lookahead: 9,
            active: 'vex',
            showBreak: true,
            combatants: [
              { id: 'vex', name: 'Vexhollow', art: 'blood-necromancer', initiative: 214, side: 'ally', health: 0.82, effects: ['glyph-spirit-vortex'] },
              { id: 'pyre', name: 'Pyre Knight', art: 'hero-emberknight', initiative: 186, side: 'ally', health: 1 },
              { id: 'maw', name: 'The Maw', art: 'blood-plague-drake', initiative: 180, side: 'enemy', health: 0.64, effects: ['glyph-magic-flame', 'glyph-cursed-eye'] },
              { id: 'ghoul', name: 'Bone Ghoul', art: 'blood-skull', initiative: 142, side: 'enemy', health: 0.3, stunned: true },
              { id: 'warden', name: 'Thornwarden', art: 'hero-vanguard', initiative: 120, side: 'ally', health: 0.55 },
              { id: 'husk', name: 'Ash Husk', art: 'blood-cursed-beast', initiative: 96, side: 'enemy', down: true },
            ],
          });
          track.on<string>('turn:advance', (id) => console.log('acting:', id));
          return track.el;
        },
        stage: 'wide',
      },
    ],
  },
  {
    id: 'BattleGrid',
    name: 'BattleGrid',
    group: 'combat',
    blurb: 'A tactics board with terrain costs, movement range flood-filled from the selected unit, and attack reach.',
    description:
      'Movement range on a tactics grid is a shortest-path problem, not a radius, and drawing it as a diamond is the classic bug: it promises tiles the rules will refuse. Here the highlight is a Dijkstra flood-fill over the same terrain costs the movement rules use, so what lights up is exactly what is reachable. Walls block, rough ground costs double, hazards are reachable but marked.',
    tags: ['tactics', 'grid', 'srpg', 'movement', 'range', 'terrain', 'pathfinding', 'board', 'hex', 'xcom'],
    related: ['InitiativeTrack', 'Tabletop', 'HousingGrid', 'DungeonMap'],
    demos: [
      {
        title: 'A skirmish in progress',
        note: 'Click a unit — its reachable tiles flood-fill through the terrain, and attack reach draws beyond them.',
        build: () => {
          const grid = new BattleGrid({
            title: 'Sunken Road',
            cols: 10,
            rows: 7,
            cell: 46,
            coords: true,
            selected: 'pyre',
            units: [
              { id: 'pyre', name: 'Pyre Knight', x: 1, y: 3, art: 'hero-emberknight', side: 'ally', health: 1, move: 4, range: 1, facing: 'e' },
              { id: 'archer', name: 'Sable Duelist', x: 0, y: 5, art: 'hero-duelist', side: 'ally', health: 0.7, move: 3, range: 4, facing: 'e' },
              { id: 'vex', name: 'Vexhollow', x: 1, y: 1, art: 'blood-necromancer', side: 'ally', health: 0.85, move: 3, range: 3, spent: true },
              { id: 'ghoul', name: 'Bone Ghoul', x: 7, y: 2, art: 'blood-skull', side: 'enemy', health: 0.45, move: 4, range: 1, facing: 'w' },
              { id: 'drake', name: 'The Maw', x: 8, y: 4, art: 'blood-plague-drake', side: 'enemy', health: 0.9, move: 3, range: 2, facing: 'w' },
            ],
            terrain: [
              { x: 4, y: 0, kind: 'wall' }, { x: 4, y: 1, kind: 'wall' }, { x: 4, y: 2, kind: 'wall' },
              { x: 4, y: 5, kind: 'wall' }, { x: 4, y: 6, kind: 'wall' },
              { x: 3, y: 3, kind: 'rough', cost: 2, label: 'Mire' },
              { x: 3, y: 4, kind: 'rough', cost: 2, label: 'Mire' },
              { x: 5, y: 3, kind: 'water', cost: 3 },
              { x: 6, y: 5, kind: 'hazard', label: 'Emberpit' },
              { x: 2, y: 2, kind: 'cover' },
              { x: 9, y: 3, kind: 'goal', label: 'Shrine' },
            ],
          });
          grid.on<{ id: string; x: number; y: number }>('grid:move', (m) => console.log('move', m));
          grid.on<{ from: string; to: string }>('grid:attack', (a) => console.log('attack', a));
          return grid.el;
        },
        stage: 'wide',
      },
    ],
  },
  {
    id: 'Reticle',
    name: 'Reticle',
    group: 'combat',
    blurb: 'The aiming crosshair: spread that opens while you move, a lock that closes on a target, and the hit chance.',
    description:
      'Spread and lock are separate numbers because they say opposite things: spread is how badly the shot will scatter, lock is how ready it is. Folding them into one bar — the mistake that makes an aiming HUD unreadable — hides the case that matters most, which is locked on and still inaccurate. Four variants cover the usual shapes, and the whole thing is CSS: no canvas, no images.',
    tags: ['reticle', 'crosshair', 'aim', 'targeting', 'spread', 'lock', 'hit chance', 'shooter', 'ranged', 'hud'],
    related: ['Nameplate', 'HUD', 'ImpactFrame', 'CastBar'],
    demos: [
      {
        title: 'Four shapes, four states',
        note: 'Left to right: tracking cross, locked brackets, ring at rest, blocked arc.',
        build: () =>
          scene('260px',
            h('div', {
              style: { position: 'absolute', inset: '0', display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', placeItems: 'center' },
            },
              new Reticle({ variant: 'cross', state: 'tracking', size: 110, spread: 0.5, lock: 0.3, target: 'Bog Warden', range: '24 m', chance: 0.72 }).el,
              new Reticle({ variant: 'brackets', state: 'locked', size: 110, spread: 0.1, lock: 1, target: 'The Maw', range: '11 m', chance: 0.94 }).el,
              new Reticle({ variant: 'ring', state: 'idle', size: 110, spread: 0.25 }).el,
              new Reticle({ variant: 'arc', state: 'blocked', size: 110, spread: 0.3, lock: 0.6, target: 'Ash Husk', range: '48 m', chance: 0.18 }).el,
            ),
          ),
        stage: 'wide',
      },
    ],
  },
  {
    id: 'KillFeed',
    name: 'KillFeed',
    group: 'combat',
    blurb: 'The running record of who killed whom, so a death is explained without pausing the fight.',
    description:
      'Each line owns its own expiry timer rather than the feed sweeping on an interval, so a line that arrives during a burst still gets its full reading time instead of being cut short by a tick that was already in flight. Every timer is registered for teardown — a feed that keeps firing after `destroy()` is the classic HUD leak. The glyph between the names is the sentence\'s verb.',
    tags: ['kill feed', 'combat log', 'hud', 'pvp', 'deaths', 'streak', 'multiplayer', 'notification', 'feed', 'shooter'],
    related: ['BattleLog', 'ToastStack', 'Nameplate', 'ObjectiveBanner'],
    demos: [
      {
        title: 'A firefight',
        note: 'New lines animate in from the edge; a headline event takes the gold bar.',
        build: () => {
          const feed = new KillFeed({
            align: 'right',
            max: 6,
            entries: [
              { actor: 'Vexhollow', target: 'Bone Ghoul', means: 'glyph-spirit-vortex', actorSide: 'ally', targetSide: 'enemy' },
              { actor: 'The Maw', target: 'Thornwarden', means: 'glyph-flaming-skull', actorSide: 'enemy', targetSide: 'ally', crit: true },
              { actor: 'Pyre Knight', target: 'Ash Husk', means: 'glyph-crossed-swords', actorSide: 'ally', targetSide: 'enemy', streak: 3 },
              { actor: 'Sable Duelist', note: 'captured the Shrine', actorSide: 'ally' },
              { actor: 'Pyre Knight', target: 'The Maw', means: 'glyph-sword-clash', actorSide: 'ally', targetSide: 'enemy', crit: true, streak: 4, headline: true },
            ],
          });
          feed.on<{ actor: string }>('feed:push', (e) => console.log('feed', e.actor));
          return scene('190px', h('div', { style: { position: 'absolute', right: '12px', top: '12px', width: '380px' } }, feed.el));
        },
        stage: 'wide',
      },
    ],
  },
  {
    id: 'PhaseTracker',
    name: 'PhaseTracker',
    group: 'combat',
    blurb: 'The round structure of a turn-based fight — upkeep, main, combat, end — with a clock on the current step.',
    description:
      '`advance()` past the last phase rolls the round over and fires `phase:round`, so the caller never has to track where the end of a round is. The clock is a one-second interval rather than a CSS animation because the number and the drain have to agree — an animated bar that finishes half a second after the digit hits zero is the sort of thing players screenshot.',
    tags: ['phase', 'turn', 'round', 'tracker', 'tcg', 'card game', 'upkeep', 'timer', 'steps', 'sequence'],
    related: ['InitiativeTrack', 'TurnMeter', 'NumberStepper', 'Tabletop'],
    demos: [
      {
        title: 'A card-game round',
        note: 'Click a phase to jump to it, or let the clock run out — `phase:timeout` fires when it does.',
        build: () => {
          const phases = new PhaseTracker({
            round: 3,
            side: 'you',
            sideLabel: 'Your turn',
            seconds: 30,
            interactive: true,
            current: 'main',
            phases: [
              { id: 'upkeep', label: 'Upkeep', icon: 'glyph-hourglass', auto: true, hint: 'Effects tick down and resources refill.' },
              { id: 'draw', label: 'Draw', icon: 'glyph-spell-book', auto: true, hint: 'Draw one card.' },
              { id: 'main', label: 'Main', icon: 'glyph-magic-staff', hint: 'Play cards, move units, use abilities.' },
              { id: 'combat', label: 'Combat', icon: 'glyph-crossed-swords', hint: 'Declare attackers, then blockers.' },
              { id: 'end', label: 'End', icon: 'glyph-skull-wreath', auto: true, hint: 'Discard down to seven.' },
            ],
          });
          phases.on<string>('phase:change', (id) => console.log('phase', id));
          phases.on('phase:timeout', () => phases.advance());
          return phases.el;
        },
        stage: 'wide',
      },
    ],
  },
];
