/**
 * FantasyUIs — painted skill & spell icon collection (235 icons).
 *
 * The source packs shipped these named by character class (`Barbarian_12.png`,
 * `FireMage_3.png`). Those class names are meaningless here — this is a general
 * icon collection, so every icon is renamed for WHAT IT DEPICTS. The `Pack_N`
 * directories survive only as the lookup key back to the original file.
 *
 * Each entry is [id, display name, search tags]; its index in the array maps to
 * `<prefix>_<index + 1>.png` inside the group's directory.
 */

const GROUPS = [
  {
    dir: 'Pack_1',
    prefix: 'Icon',
    /** Tags every icon in the group inherits. */
    common: ['rune', 'sigil', 'arcane', 'buff'],
    items: [
      ['rune-crystal-shard', 'Crystal Shard Rune', 'crystal shard ice blue gem'],
      ['rune-radiant-gem', 'Radiant Gem', 'gem jewel light burst gold'],
      ['rune-ember-mark', 'Ember Mark', 'flame fire gold glyph'],
      ['rune-trident-mark', 'Trident Mark', 'trident three prong gold'],
      ['rune-starfall', 'Starfall Sigil', 'star burst spark green gold'],
      ['crest-stone-guard', 'Stone Guard Crest', 'shield stone crest defence'],
      ['rune-verdant-totem', 'Verdant Totem', 'nature totem green tree'],
      ['rune-sealed-ring', 'Sealed Ring', 'ring seal binding gold teal'],
      ['rune-gilded-script', 'Gilded Script', 'script writing gold scroll'],
      ['rune-fractured-stone', 'Fractured Stone', 'cracked stone broken gold'],
      ['rune-jade-coin', 'Jade Coin', 'coin jade token teal currency'],
      ['rune-emerald-seal', 'Emerald Seal', 'seal emerald green hexagon'],
      ['rune-eclipse-mark', 'Eclipse Mark', 'eclipse circle slash gold'],
      ['rune-flame-sigil', 'Flame Sigil', 'flame circle fire gold'],
      ['rune-astral-burst', 'Astral Burst', 'astral star blue gold orb'],
      ['rune-bronze-disc', 'Bronze Disc', 'disc bronze medal token'],
      ['rune-radiance', 'Radiance Sigil', 'radiance holy light gold'],
      ['crest-warded-shield', 'Warded Shield', 'shield ward stone protection'],
      ['rune-silver-knot', 'Silver Knot', 'knot celtic silver disc'],
      ['icon-blade-chalice', 'Blade Chalice', 'chalice blade offering ritual'],
      ['crest-sacred-anchor', 'Sacred Anchor', 'anchor holy cross white crest'],
      ['crest-gilded-crown', 'Gilded Crown', 'crown king royal gold rank'],
      ['orb-emberstorm', 'Emberstorm Orb', 'orb fire storm blue gold'],
      ['orb-frostwind', 'Frostwind Orb', 'orb frost ice teal swirl'],
      ['orb-voidspiral', 'Void Spiral Orb', 'orb void purple vortex spiral'],
      ['crest-ember-shield', 'Ember Shield', 'shield fire ember orange'],
      ['icon-astrolabe', 'Astrolabe', 'astrolabe compass navigation gold'],
      ['icon-casting-hand', 'Casting Hand', 'hand cast spell magic touch'],
      ['icon-meditation', 'Meditation', 'monk meditate focus calm zen'],
      ['fx-golden-eruption', 'Golden Eruption', 'eruption geyser gold blast'],
      ['fx-verdant-bolt', 'Verdant Bolt', 'lightning green nature bolt'],
      ['fx-storm-bolt', 'Storm Bolt', 'lightning blue storm thunder'],
      ['fx-nature-surge', 'Nature Surge', 'nature green energy roots'],
      ['fx-emerald-blaze', 'Emerald Blaze', 'green fire blaze leaves'],
      ['fx-thorn-bloom', 'Thorn Bloom', 'thorn leaf teal bloom nature'],
      ['fx-vine-lash', 'Vine Lash', 'vine whip green nature entangle'],
      ['fx-lotus-spring', 'Lotus Spring', 'lotus flower water gold heal'],
      ['fx-molten-core', 'Molten Core', 'molten lava sphere core fire'],
      ['fx-frost-comet', 'Frost Comet', 'comet meteor ice blue'],
      ['fx-solar-vortex', 'Solar Vortex', 'vortex sun gold eye spiral'],
    ],
  },
  {
    dir: 'Pack_2',
    prefix: 'Barbarian',
    common: ['melee', 'warrior', 'combat', 'physical'],
    items: [
      ['orb-verdant-ring', 'Verdant Ring', 'orb green ring shield barrier'],
      ['hero-warrior-stand', 'Warrior', 'warrior fighter man stance hero'],
      ['skill-titan-fist', 'Titan Fist', 'fist punch giant smash mountain'],
      ['crest-warmark', 'War Mark', 'crest emblem war gold banner'],
      ['rune-nova-star', 'Nova Star', 'star nova blue burst dark'],
      ['hero-brute', 'Brute', 'brute strongman muscle barbarian hero'],
      ['hero-stormblade', 'Stormblade', 'warrior lightning storm hero'],
      ['hero-lone-wanderer', 'Lone Wanderer', 'traveller cliff journey hero'],
      ['hero-green-sorceress', 'Sorceress', 'sorceress witch mage woman hero'],
      ['hero-emberknight', 'Ember Knight', 'knight armour fire hero'],
      ['hero-spellblade', 'Spellblade', 'mage sword battlemage hero'],
      ['hero-blue-cultist', 'Cultist', 'hooded cultist robe blue hero'],
      ['hero-vanguard', 'Vanguard', 'soldier leap charge green hero'],
      ['hero-duelist', 'Duelist', 'rogue dual blades assassin hero'],
      ['hero-voidguard', 'Voidguard', 'armoured purple lightning hero'],
      ['rune-obsidian-seal', 'Obsidian Seal', 'seal dark hexagon obsidian gold'],
      ['weapon-longsword-gold', 'Gilded Longsword', 'sword longsword gold weapon'],
      ['weapon-longsword-red', 'Crimson Longsword', 'sword red weapon blade'],
      ['weapon-runeblade', 'Runeblade', 'sword rune blue purple weapon'],
      ['weapon-warhammer', 'Warhammer', 'hammer maul warhammer weapon'],
      ['weapon-battleaxe', 'Battleaxe', 'axe battleaxe weapon chop'],
      ['weapon-cleaver-axe', 'Cleaver Axe', 'axe cleaver white weapon'],
      ['weapon-thunderblade', 'Thunderblade', 'sword lightning thunder weapon'],
      ['skill-crushing-grip', 'Crushing Grip', 'gauntlet grip crush stone hand'],
      ['hero-stone-golem', 'Stone Golem', 'golem stone construct teal hero'],
      ['weapon-flameblade', 'Flameblade', 'sword fire flame weapon'],
      ['weapon-hatchet', 'Hatchet', 'axe hatchet pick weapon'],
      ['weapon-broadsword', 'Broadsword', 'sword broadsword greatsword weapon'],
      ['weapon-magma-sword', 'Magma Sword', 'sword lava magma weapon'],
      ['weapon-chain-hook', 'Chain Hook', 'hook chain grapple pull weapon'],
      ['weapon-frost-axe', 'Frost Axe', 'axe ice frost weapon'],
      ['skill-iron-fist', 'Iron Fist', 'gauntlet fist punch armour strike'],
      ['fx-crimson-shock', 'Crimson Shock', 'red shockwave impact blast'],
      ['hero-nightwatch', 'Nightwatch', 'knight armour night guard hero'],
      ['weapon-ceremonial-mace', 'Ceremonial Mace', 'mace sceptre gold weapon'],
      ['weapon-obsidian-mace', 'Obsidian Mace', 'mace club dark weapon'],
      ['skill-whirlwind', 'Whirlwind', 'spin sweep arc attack warrior'],
      ['weapon-sunblade', 'Sunblade', 'sword holy gold flame weapon'],
      ['hero-berserker', 'Berserker', 'berserker rage green aura hero'],
      ['hero-demon-lord', 'Demon Lord', 'demon horned boss blue hero'],
    ],
  },
  {
    dir: 'Pack_3',
    prefix: 'EarthMage',
    common: ['earth', 'stone', 'nature', 'mineral'],
    items: [
      ['earth-crystal-meteor', 'Crystal Meteor', 'meteor crystal falling impact'],
      ['earth-falling-gem', 'Falling Gem', 'gem falling ruby drop'],
      ['earth-gem-boulder', 'Gem Boulder', 'boulder rock gems ore'],
      ['earth-golden-shell', 'Golden Shell', 'shell carapace gold armour'],
      ['earth-stone-spike', 'Stone Spike', 'spike stone impale thorn'],
      ['earth-rock-spire', 'Rock Spire', 'spire rock pillar formation'],
      ['earth-dark-crystal', 'Dark Crystal', 'crystal dark green shard'],
      ['earth-molten-vein', 'Molten Vein', 'vein molten gold lava rock'],
      ['earth-stone-blade', 'Stone Blade', 'blade stone shard weapon'],
      ['earth-quartz-beam', 'Quartz Beam', 'beam quartz white light'],
      ['earth-meteor-shower', 'Meteor Shower', 'meteor shower rocks falling'],
      ['earth-gilded-rock', 'Gilded Rock', 'rock gold nugget ore'],
      ['earth-serpent-eye', 'Serpent Eye', 'eye serpent dragon reptile green'],
      ['earth-citrine-shard', 'Citrine Shard', 'crystal citrine gold shard'],
      ['earth-lightspike', 'Light Spike', 'spike light gold pierce'],
      ['earth-runestone-disc', 'Runestone Disc', 'runestone disc dark rune'],
      ['earth-geode-crystal', 'Geode Crystal', 'geode crystal white cave'],
      ['earth-rune-arch', 'Rune Arch', 'arch rune green gateway'],
      ['earth-fractured-block', 'Fractured Block', 'block cracked stone break'],
      ['earth-amethyst-cluster', 'Amethyst Cluster', 'amethyst purple crystal cluster'],
      ['earth-sapphire-shard', 'Sapphire Shard', 'sapphire blue crystal shard'],
      ['earth-monolith', 'Monolith', 'monolith pillar standing stone'],
      ['earth-emerald-burst', 'Emerald Burst', 'emerald green gems burst'],
      ['earth-golden-seed', 'Golden Seed', 'seed pod gold growth'],
      ['earth-stone-ring', 'Stone Ring', 'ring stone circle henge'],
      ['earth-sunstone-ring', 'Sunstone Ring', 'ring gold glowing sunstone'],
      ['earth-star-medallion', 'Star Medallion', 'medallion star gold octagon'],
      ['earth-verdant-ward', 'Verdant Ward', 'ward green shield nature'],
      ['earth-lava-well', 'Lava Well', 'well pit lava fire stone'],
      ['earth-crystal-bloom', 'Crystal Bloom', 'bloom flower crystal growth'],
      ['earth-fungal-stone', 'Fungal Stone', 'mushroom fungus stone teal'],
      ['earth-fissure-web', 'Fissure Web', 'fissure cracks web gold'],
      ['earth-cobble-glow', 'Glowing Cobble', 'cobblestone path glow light'],
      ['earth-boulder-fist', 'Boulder Fist', 'boulder fist rock punch'],
      ['earth-magma-crust', 'Magma Crust', 'magma crust cracked purple'],
      ['earth-scorched-plain', 'Scorched Plain', 'scorched cracked ground drought'],
      ['earth-frozen-core', 'Frozen Core', 'frozen core blue crystal pit'],
      ['earth-obsidian-rift', 'Obsidian Rift', 'rift obsidian lava purple'],
      ['earth-slate-slabs', 'Slate Slabs', 'slate slabs blue rock wall'],
      ['earth-mossy-stone', 'Mossy Stone', 'moss stone green wall brick'],
    ],
  },
  {
    dir: 'Pack_4',
    prefix: 'FireMage',
    common: ['fire', 'flame', 'burn', 'elemental'],
    items: [
      ['fire-emerald-comet', 'Emerald Comet', 'comet green crystal trail'],
      ['fire-flame-lance', 'Flame Lance', 'lance spear fire pierce'],
      ['fire-inferno-eye', 'Inferno Eye', 'eye fire inferno blue core'],
      ['fire-rock-blaze', 'Rock Blaze', 'blaze rocks fire eruption'],
      ['fire-crimson-swirl', 'Crimson Swirl', 'swirl red fire spiral'],
      ['fire-flame-drop', 'Flame Drop', 'flame teardrop fire single'],
      ['fire-searing-streak', 'Searing Streak', 'streak searing fire dash'],
      ['fire-twin-flames', 'Twin Flames', 'twin double flames gold'],
      ['fire-volcano', 'Volcano', 'volcano eruption lava mountain'],
      ['fire-flame-burst', 'Flame Burst', 'burst flame explosion orange'],
      ['fire-cross-blast', 'Cross Blast', 'cross blast fire star'],
      ['fire-golden-flame', 'Golden Flame', 'flame gold holy fire'],
      ['fire-palm-flame', 'Palm Flame', 'hand palm flame cast fire'],
      ['fire-dragon-eye', 'Dragon Eye', 'eye dragon slit reptile fire'],
      ['fire-ember-eye', 'Ember Eye', 'eye ember dark ring fire'],
      ['fire-hellhound', 'Hellhound', 'hound beast fire demon head'],
      ['fire-slash', 'Fire Slash', 'slash cut fire diagonal'],
      ['fire-flame-ring', 'Flame Ring', 'ring circle fire barrier'],
      ['fire-solar-beam', 'Solar Beam', 'beam solar light bright fire'],
      ['fire-whitehot-blade', 'White-Hot Blade', 'blade sword white hot fire'],
      ['fire-molten-heart', 'Molten Heart', 'heart molten core red fire'],
      ['fire-sun-sigil', 'Sun Sigil', 'sun star sigil gold ring'],
      ['fire-flame-volley', 'Flame Volley', 'volley arrows fire upward'],
      ['fire-basilisk-eye', 'Basilisk Eye', 'eye basilisk green rim fire'],
      ['fire-phoenix-rise', 'Phoenix Rise', 'phoenix rise rebirth fire bird'],
      ['fire-sunburst', 'Sunburst', 'sunburst star explosion light'],
      ['fire-meteor', 'Meteor', 'meteor sphere falling gold'],
      ['fire-void-flame', 'Void Flame', 'void flame black red swirl'],
      ['fire-dragon-roar', 'Dragon Roar', 'dragon roar head blue gold'],
      ['fire-steam-vortex', 'Steam Vortex', 'vortex steam fire water swirl'],
      ['fire-lava-floor', 'Lava Floor', 'lava floor tiles ground'],
      ['fire-arcane-ring', 'Arcane Fire Ring', 'ring fire arcane blue core'],
      ['fire-immolation', 'Immolation', 'immolation figure burning fire'],
      ['fire-frostfire', 'Frostfire', 'frostfire ice crystal flame'],
      ['fire-firenado', 'Firenado', 'tornado fire whirlwind lava'],
      ['fire-phoenix-flight', 'Phoenix Flight', 'phoenix bird flight gold fire'],
      ['fire-magma-spikes', 'Magma Spikes', 'magma spikes crystal lava'],
      ['fire-lava-field', 'Lava Field', 'lava field landscape molten'],
      ['fire-lava-flow', 'Lava Flow', 'lava flow river rocks'],
      ['fire-radiant-dawn', 'Radiant Dawn', 'dawn radiance beams gold light'],
    ],
  },
  {
    dir: 'Pack_5',
    prefix: 'Hunter',
    common: ['ranged', 'beast', 'hunt', 'nature'],
    items: [
      ['hunt-beast-pack', 'Beast Pack', 'beasts pack wolves summon animals'],
      ['hunt-golden-bow', 'Golden Bow', 'bow gold ranged weapon'],
      ['hunt-crossbow', 'Crossbow', 'crossbow ranged weapon purple'],
      ['hunt-emerald-orb', 'Emerald Orb', 'orb emerald green sphere'],
      ['hunt-hand-cannon', 'Hand Cannon', 'gun cannon blunderbuss ranged'],
      ['hunt-arrow-orb', 'Arrow Orb', 'orb arrows blue sphere'],
      ['hunt-prowling-cat', 'Prowling Cat', 'leopard cat beast prowl animal'],
      ['hunt-verdant-spikes', 'Verdant Spikes', 'spikes green crystal thorns'],
      ['hunt-dire-wolf', 'Dire Wolf', 'wolf dire beast head animal'],
      ['hunt-jade-carapace', 'Jade Carapace', 'shell carapace jade green armour'],
      ['hunt-jade-dagger', 'Jade Dagger', 'dagger knife jade green weapon'],
      ['hunt-venom-dart', 'Venom Dart', 'dart venom poison green weapon'],
      ['hunt-frost-bolt', 'Frost Bolt', 'bolt arrow frost blue ranged'],
      ['hunt-piercing-arrow', 'Piercing Arrow', 'arrow pierce red blue ranged'],
      ['hunt-star-dagger', 'Star Dagger', 'dagger ornate stars night weapon'],
      ['hunt-tracking-ring', 'Tracking Ring', 'ring track arrow gold compass'],
      ['hunt-leaf-blade', 'Leaf Blade', 'blade leaf green nature weapon'],
      ['hunt-arrow-storm', 'Arrow Storm', 'arrows storm volley ranged'],
      ['hunt-crow-swarm', 'Crow Swarm', 'crows birds swarm flock dark'],
      ['hunt-bird-flight', 'Bird Flight', 'birds flight flock sky blue'],
      ['hunt-night-flock', 'Night Flock', 'birds flock night purple dusk'],
      ['hunt-gilded-blade', 'Gilded Blade', 'blade gold purple weapon'],
      ['hunt-golden-egg', 'Golden Egg', 'egg cocoon gold hatch'],
      ['hunt-frost-spear', 'Frost Spear', 'spear frost teal ice weapon'],
      ['hunt-venom-flask', 'Venom Flask', 'flask potion venom green poison'],
    ],
  },
  {
    dir: 'Pack_6',
    prefix: 'Engineer',
    common: ['tech', 'device', 'gadget', 'craft'],
    items: [
      ['tech-mortar', 'Mortar', 'mortar cannon artillery siege'],
      ['tech-power-gauntlet', 'Power Gauntlet', 'gauntlet mechanical arm teal'],
      ['tech-warp-disc', 'Warp Disc', 'portal warp disc teleport'],
      ['tech-prism-darts', 'Prism Darts', 'darts prism crystal colourful'],
      ['tech-piston-fist', 'Piston Fist', 'fist piston metal punch'],
      ['tech-flame-drill', 'Flame Drill', 'drill flame bore lava'],
      ['tech-toxic-skull', 'Toxic Skull', 'skull toxic gas smoke blue'],
      ['tech-mech-suit', 'Mech Suit', 'mech suit robot green'],
      ['tech-energy-shield', 'Energy Shield', 'shield energy barrier blue'],
      ['tech-blade-forge', 'Blade Forge', 'forge blade craft anvil green'],
      ['tech-chrono-watch', 'Chrono Watch', 'watch clock time gold teal'],
      ['tech-tesla-hammer', 'Tesla Hammer', 'hammer lightning electric tesla'],
      ['tech-arc-lantern', 'Arc Lantern', 'lantern lamp light gold blue'],
      ['tech-signal-horn', 'Signal Horn', 'horn signal call device gold'],
      ['tech-flamethrower', 'Flamethrower', 'flamethrower fire spray weapon'],
      ['tech-beam-turret', 'Beam Turret', 'turret beam tower green'],
      ['tech-shock-mine', 'Shock Mine', 'mine bomb spiked shock blue'],
      ['tech-plasma-orb', 'Plasma Orb', 'orb plasma blue device'],
      ['tech-serum-injector', 'Serum Injector', 'syringe injector serum teal'],
      ['tech-toxin-bomb', 'Toxin Bomb', 'bomb toxin green grenade'],
      ['tech-compass', 'Compass', 'compass navigation direction gold'],
      ['tech-coolant-flask', 'Coolant Flask', 'flask coolant blue potion'],
      ['tech-lance-cannon', 'Lance Cannon', 'cannon lance beam gold'],
      ['tech-frost-cannon', 'Frost Cannon', 'cannon frost water blue spray'],
      ['tech-alchemy-pour', 'Alchemy Pour', 'pour liquid alchemy blue flask'],
    ],
  },
  {
    dir: 'Pack_7',
    prefix: 'BloodMage',
    common: ['blood', 'dark', 'curse', 'shadow'],
    items: [
      ['blood-crimson-gate', 'Crimson Gate', 'gate portal red stone dark'],
      ['blood-ritualist', 'Ritualist', 'ritual figure summon red hero'],
      ['blood-witch', 'Blood Witch', 'witch sorceress red robe hero'],
      ['blood-hex-mark', 'Hex Mark', 'hex mark sigil red curse'],
      ['blood-purge-burst', 'Purge Burst', 'burst white light purge red'],
      ['blood-soul-ribbon', 'Soul Ribbon', 'soul ribbon aurora pink spirit'],
      ['blood-bleeding-knife', 'Bleeding Knife', 'knife blood bleed dagger'],
      ['blood-fountain', 'Blood Fountain', 'fountain geyser blood red ring'],
      ['blood-shard-burst', 'Shard Burst', 'shard burst pink crystal'],
      ['blood-toxin-flow', 'Toxin Flow', 'toxin flow green red poison'],
      ['blood-corruption', 'Corruption', 'corruption swirl red green taint'],
      ['blood-vein-crack', 'Vein Crack', 'veins cracks red lightning'],
      ['blood-sanguine-blade', 'Sanguine Blade', 'sword blade white red weapon'],
      ['blood-nightwing', 'Nightwing', 'bat wing dark red night'],
      ['blood-hex-circle', 'Hex Circle', 'circle target rings red blue'],
      ['blood-serpent-coil', 'Serpent Coil', 'serpent snake coil red'],
      ['blood-pale-priest', 'Pale Priest', 'priest robed white caster hero'],
      ['blood-crimson-moon', 'Crimson Moon', 'moon sphere red planet'],
      ['blood-chalice', 'Blood Chalice', 'chalice goblet cup dark ritual'],
      ['blood-void-lance', 'Void Lance', 'lance spear purple void weapon'],
      ['blood-plague-drake', 'Plague Drake', 'drake dragon green plague'],
      ['blood-cursed-beast', 'Cursed Beast', 'beast cursed dark green rune'],
      ['blood-skull', 'Blood Skull', 'skull red death bone'],
      ['blood-necromancer', 'Necromancer', 'necromancer caster dark green hero'],
      ['blood-altar', 'Blood Altar', 'altar stone ritual sacrifice red'],
    ],
  },
];

export const SPELL_ICONS = GROUPS.flatMap((g) =>
  g.items.map(([id, name, tags], i) => ({
    src: `${g.dir}/${g.prefix}_${i + 1}.png`,
    id,
    name,
    category: 'icon',
    // Opaque painted tiles — WebP is far smaller than PNG and loses nothing here.
    format: 'webp',
    maxW: 256,
    tags: [...new Set([...tags.split(' '), ...g.common, 'skill', 'ability'])],
    slice: null,
  })),
);
