/**
 * Regenerates the library's barrel export and master stylesheet from whatever
 * lives in src/lib/components/. Run after adding a component so it is exported
 * and its CSS is bundled without touching either index by hand.
 */
import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const COMPONENTS = path.join(ROOT, 'src', 'lib', 'components');

/** Components whose CSS must load before others that build on top of them. */
const CSS_ORDER = ['Panel', 'Button', 'Icon', 'StatBar', 'Slot'];

export async function genLib() {
  const files = await readdir(COMPONENTS);
  const names = files
    .filter((f) => f.endsWith('.ts'))
    .map((f) => f.replace(/\.ts$/, ''))
    .sort();
  const cssNames = files.filter((f) => f.endsWith('.css')).map((f) => f.replace(/\.css$/, ''));

  const ordered = [
    ...CSS_ORDER.filter((n) => cssNames.includes(n)),
    ...cssNames.filter((n) => !CSS_ORDER.includes(n)).sort(),
  ];

  const css = `/* AUTO-GENERATED by scripts/gen-lib.mjs — do not edit by hand.
   FantasyUIs master stylesheet. Import this once and every component is styled.
   Order matters: asset variables, then tokens, then themes, then components. */

@import './assets.css';
@import './base.css';
@import './theme-stone-vine.css';
@import './theme-dark-ember.css';

${ordered.map((n) => `@import '../components/${n}.css';`).join('\n')}
`;
  await writeFile(path.join(ROOT, 'src', 'lib', 'styles', 'index.css'), css, 'utf8');

  const barrel = `// AUTO-GENERATED by scripts/gen-lib.mjs — do not edit by hand.
// The FantasyUIs public surface. Import components individually for the
// smallest bundle, or pull from here for convenience.

export * from './core/component.ts';
export * from './core/dom.ts';
export * from './core/assets.ts';
export * from '../data/assets.generated.ts';

${names.map((n) => `export * from './components/${n}.ts';`).join('\n')}
`;
  await writeFile(path.join(ROOT, 'src', 'lib', 'index.ts'), barrel, 'utf8');

  return { components: names, styles: ordered };
}

if (import.meta.filename === process.argv[1]) {
  const r = await genLib();
  console.log(`✓ barrel + stylesheet regenerated for ${r.components.length} components`);
}
