import { FuiComponent, type BaseOptions } from '../core/component.ts';
import { h, clear, clamp } from '../core/dom.ts';

export interface Combatant {
  id: string;
  name?: string;
  /** Manifest asset id for the portrait. */
  art?: string;
  /** Initiative or speed. Higher goes first. */
  initiative?: number;
  /** Side, which colours the marker. */
  side?: 'ally' | 'enemy' | 'neutral';
  /** Health left, 0–1, drawn as a ring. */
  health?: number;
  /** Status glyph asset ids. */
  effects?: string[];
  /** Out of the fight — kept in the order, drawn as gone. */
  down?: boolean;
  /** Skipping its next turn. */
  stunned?: boolean;
  /** Turns until it acts again. Overrides its place in the queue. */
  delay?: number;
}

export interface InitiativeTrackOptions extends BaseOptions {
  /** Everyone in the fight. Order is worked out from initiative. */
  combatants: Combatant[];
  /** Whose turn it is. */
  active?: string;
  /** How many upcoming turns to show. */
  lookahead?: number;
  /** Heading over the track. */
  title?: string;
  /** Round number, printed beside the title. */
  round?: number;
  /** Portrait size in pixels. */
  size?: number;
  /** Draw the round-break marker in the queue. */
  showBreak?: boolean;
}

/**
 * The turn order: who acts now, who is next, and how far away your turn is.
 * `TurnMeter` shows speed bars filling; this shows the resulting queue, which
 * is what a player actually plans against.
 *
 *   const track = new InitiativeTrack({
 *     title: 'Turn order', round: 3, lookahead: 8, active: 'vex',
 *     combatants: [
 *       { id: 'vex', name: 'Vexhollow', art: 'blood-necromancer', initiative: 214, side: 'ally', health: 0.8 },
 *       { id: 'boss', name: 'The Maw', art: 'blood-plague-drake', initiative: 180, side: 'enemy', health: 1 },
 *     ],
 *   });
 *   track.on<string>('turn:advance', (id) => battle.begin(id));
 *
 * The queue is generated by cycling the order until it has enough entries, so
 * a lookahead longer than the party wraps into the next round and shows the
 * break — which is the moment a player is really planning around. A stunned
 * combatant keeps its slot and is marked as skipping, rather than vanishing:
 * a queue that silently drops a unit is a queue nobody can trust.
 */
export class InitiativeTrack extends FuiComponent<InitiativeTrackOptions> {
  private queue: HTMLElement;

  constructor(opts: InitiativeTrackOptions) {
    const root = h('div', {
      class: 'fui fui-init',
      style: { '--fui-init-size': `${opts.size ?? 46}px` },
    });
    super(root, opts);

    if (opts.title || opts.round != null) {
      const head = h('div', { class: 'fui-init__head' });
      if (opts.title) {
        head.appendChild(h('span', { class: 'fui-init__title fui-label', text: opts.title }));
      }
      if (opts.round != null) {
        head.appendChild(h('span', { class: 'fui-init__round fui-num', text: `Round ${opts.round}` }));
      }
      root.appendChild(head);
    }

    this.queue = h('div', { class: 'fui-init__queue' });
    root.appendChild(this.queue);
    this.render();
  }

  /** The fight's order, fastest first, with the downed left out. */
  order(): Combatant[] {
    return this.opts.combatants
      .filter((c) => !c.down)
      .slice()
      .sort((a, b) => (b.initiative ?? 0) - (a.initiative ?? 0));
  }

  /** Whose turn it is. */
  current(): Combatant | undefined {
    return this.opts.combatants.find((c) => c.id === this.opts.active);
  }

  /** How many turns until a combatant acts, or -1 if it never will. */
  turnsUntil(id: string): number {
    return this.upcoming().findIndex((e) => e.combatant.id === id);
  }

  /** Move to the next combatant. */
  advance(): this {
    const list = this.upcoming();
    const next = list[1] ?? list[0];
    if (!next) return this;
    this.opts.active = next.combatant.id;
    if (next.round > 0 && this.opts.round != null) this.opts.round += next.round;
    this.render();
    this.emit('turn:advance', next.combatant.id);
    return this;
  }

  /** Replace the roster mid-fight — a summon, a death, a speed buff. */
  setCombatants(combatants: Combatant[]): this {
    this.opts.combatants = combatants;
    this.render();
    return this;
  }

  /**
   * The queue, starting at whoever is active. Cycling the order rather than
   * slicing it is what lets a lookahead longer than the party wrap into the
   * next round and show the break.
   */
  private upcoming(): Array<{ combatant: Combatant; round: number }> {
    const order = this.order();
    if (!order.length) return [];
    const startAt = Math.max(0, order.findIndex((c) => c.id === this.opts.active));
    const want = clamp(this.opts.lookahead ?? 8, 1, 40);
    const out: Array<{ combatant: Combatant; round: number }> = [];
    for (let i = 0; i < want; i++) {
      const index = (startAt + i) % order.length;
      out.push({ combatant: order[index], round: Math.floor((startAt + i) / order.length) });
    }
    return out;
  }

  private render(): void {
    clear(this.queue);
    const list = this.upcoming();
    let seenRound = 0;

    list.forEach((entry, i) => {
      // The round break is the moment a player is really planning around.
      if ((this.opts.showBreak ?? true) && entry.round > seenRound) {
        seenRound = entry.round;
        this.queue.appendChild(
          h('span', {
            class: 'fui-init__break',
            text: this.opts.round != null ? `Round ${this.opts.round + entry.round}` : 'Next round',
          }),
        );
      }

      const c = entry.combatant;
      const cell = h('div', {
        class: 'fui-init__slot',
        dataset: {
          side: c.side ?? 'neutral',
          active: String(i === 0),
          stunned: String(!!c.stunned),
        },
        style: { '--fui-init-hp': String(clamp(c.health ?? 1, 0, 1)) },
        attrs: { title: `${c.name ?? c.id}${c.stunned ? ' — skipping' : ''}` },
      });

      const ring = h('span', { class: 'fui-init__ring' });
      const art = h('span', { class: 'fui-init__art' });
      if (c.art) art.style.backgroundImage = `var(--fui-img-${c.art})`;
      ring.appendChild(art);
      cell.appendChild(ring);

      if (c.effects?.length) {
        const pips = h('span', { class: 'fui-init__effects' });
        for (const glyph of c.effects.slice(0, 3)) {
          pips.appendChild(
            h('span', {
              class: 'fui-init__effect',
              style: { '--fui-glyph-src': `var(--fui-img-${glyph})` },
            }),
          );
        }
        cell.appendChild(pips);
      }

      if (c.stunned) cell.appendChild(h('span', { class: 'fui-init__skip', text: 'Skip' }));
      if (c.name) cell.appendChild(h('span', { class: 'fui-init__name', text: c.name }));
      if (i === 0 && c.initiative != null) {
        cell.appendChild(h('span', { class: 'fui-init__speed fui-num', text: String(c.initiative) }));
      }
      this.queue.appendChild(cell);
    });

    // Downed combatants sit at the end so the roster stays complete: a queue
    // that silently drops a unit is a queue nobody can trust.
    for (const c of this.opts.combatants.filter((x) => x.down)) {
      const cell = h('div', {
        class: 'fui-init__slot',
        dataset: { side: c.side ?? 'neutral', down: 'true' },
        attrs: { title: `${c.name ?? c.id} — down` },
      });
      const ring = h('span', { class: 'fui-init__ring' });
      const art = h('span', { class: 'fui-init__art' });
      if (c.art) art.style.backgroundImage = `var(--fui-img-${c.art})`;
      ring.appendChild(art);
      cell.appendChild(ring);
      if (c.name) cell.appendChild(h('span', { class: 'fui-init__name', text: c.name }));
      this.queue.appendChild(cell);
    }
  }
}
