// AUTO-GENERATED by scripts/ingest.mjs — do not edit by hand.
// Run `npm run ingest` after dropping new art into new_assets/.

/** 9-slice inset in output pixels, ordered [top, right, bottom, left]. */
export type Slice = [number, number, number, number];

export type AssetCategory =
  | 'background'
  | 'banner'
  | 'bar'
  | 'button'
  | 'decor'
  | 'frame'
  | 'icon'
  | 'panel'
  | 'silhouette'
  | 'slot';

export interface AssetRecord {
  /** Stable identifier, unique within its pack. */
  id: string;
  /** Owning pack / theme id. */
  pack: string;
  /** Human-readable label. */
  name: string;
  category: AssetCategory;
  tags: string[];
  /** Path relative to the asset base, e.g. "stone-vine/panel-stone.png". */
  file: string;
  /** Small WebP preview, site gallery only. */
  thumb: string;
  width: number;
  height: number;
  /** 9-slice insets, or null when the art must keep its natural aspect ratio. */
  slice: Slice | null;
  bytes: number;
}

export interface PackRecord {
  id: string;
  name: string;
  blurb: string;
  accent: string;
  count: number;
}

export const PACKS: PackRecord[] = [
  {
    "id": "stone-vine",
    "name": "Stone & Vine",
    "blurb": "Carved grey stone framing with celtic vine ornaments, teal button faces and painted RPG item icons. Reads as adventure, exploration and town UI.",
    "accent": "#6fb3a8",
    "count": 37
  },
  {
    "id": "dark-ember",
    "name": "Dark Ember",
    "blurb": "Thin bronze art-deco framing over black leather, with glossy blood-red buttons and glowing spell icons. Reads as combat, dark fantasy and endgame UI.",
    "accent": "#c2764a",
    "count": 42
  }
];

export const ASSETS: AssetRecord[] = [
  {
    "id": "banner-arrow",
    "pack": "dark-ember",
    "name": "Name Banner (Arrow)",
    "category": "banner",
    "tags": [
      "banner",
      "nameplate",
      "label",
      "arrow",
      "ribbon"
    ],
    "file": "dark-ember/banner-arrow.png",
    "thumb": "dark-ember/thumb/banner-arrow.webp",
    "width": 1024,
    "height": 256,
    "slice": [
      40,
      150,
      40,
      40
    ],
    "bytes": 37263
  },
  {
    "id": "banner-dark",
    "pack": "dark-ember",
    "name": "Name Banner (Dark)",
    "category": "banner",
    "tags": [
      "banner",
      "nameplate",
      "label",
      "header",
      "subtle"
    ],
    "file": "dark-ember/banner-dark.png",
    "thumb": "dark-ember/thumb/banner-dark.webp",
    "width": 1024,
    "height": 256,
    "slice": [
      40,
      40,
      40,
      40
    ],
    "bytes": 20374
  },
  {
    "id": "banner-plain",
    "pack": "dark-ember",
    "name": "Name Banner (Plain)",
    "category": "banner",
    "tags": [
      "banner",
      "nameplate",
      "label",
      "header"
    ],
    "file": "dark-ember/banner-plain.png",
    "thumb": "dark-ember/thumb/banner-plain.webp",
    "width": 1024,
    "height": 256,
    "slice": [
      40,
      40,
      40,
      40
    ],
    "bytes": 36007
  },
  {
    "id": "bar-fill-ember",
    "pack": "dark-ember",
    "name": "Ember Fill (Red)",
    "category": "bar",
    "tags": [
      "bar",
      "fill",
      "red",
      "health",
      "hp",
      "blood"
    ],
    "file": "dark-ember/bar-fill-ember.png",
    "thumb": "dark-ember/thumb/bar-fill-ember.webp",
    "width": 1024,
    "height": 64,
    "slice": [
      14,
      22,
      14,
      22
    ],
    "bytes": 23808
  },
  {
    "id": "bar-track-ember",
    "pack": "dark-ember",
    "name": "Ember Bar Track",
    "category": "bar",
    "tags": [
      "bar",
      "track",
      "thin",
      "health",
      "progress"
    ],
    "file": "dark-ember/bar-track-ember.png",
    "thumb": "dark-ember/thumb/bar-track-ember.webp",
    "width": 1024,
    "height": 64,
    "slice": [
      16,
      26,
      16,
      26
    ],
    "bytes": 2990
  },
  {
    "id": "bg-round-sm",
    "pack": "dark-ember",
    "name": "Round Backdrop",
    "category": "background",
    "tags": [
      "background",
      "round",
      "circle",
      "skill",
      "fill"
    ],
    "file": "dark-ember/bg-round-sm.png",
    "thumb": "dark-ember/thumb/bg-round-sm.webp",
    "width": 64,
    "height": 64,
    "slice": null,
    "bytes": 3300
  },
  {
    "id": "bg-tall",
    "pack": "dark-ember",
    "name": "Leather Backdrop (Tall)",
    "category": "background",
    "tags": [
      "background",
      "leather",
      "texture",
      "fill"
    ],
    "file": "dark-ember/bg-tall.png",
    "thumb": "dark-ember/thumb/bg-tall.webp",
    "width": 800,
    "height": 1200,
    "slice": [
      23,
      23,
      23,
      23
    ],
    "bytes": 108865
  },
  {
    "id": "bg-tile-sm",
    "pack": "dark-ember",
    "name": "Leather Tile (Small)",
    "category": "background",
    "tags": [
      "background",
      "tile",
      "texture",
      "fill",
      "slot"
    ],
    "file": "dark-ember/bg-tile-sm.png",
    "thumb": "dark-ember/thumb/bg-tile-sm.webp",
    "width": 256,
    "height": 256,
    "slice": [
      24,
      24,
      24,
      24
    ],
    "bytes": 42482
  },
  {
    "id": "bg-wide",
    "pack": "dark-ember",
    "name": "Leather Backdrop (Wide)",
    "category": "background",
    "tags": [
      "background",
      "leather",
      "texture",
      "fill"
    ],
    "file": "dark-ember/bg-wide.png",
    "thumb": "dark-ember/thumb/bg-wide.webp",
    "width": 1024,
    "height": 512,
    "slice": [
      30,
      30,
      30,
      30
    ],
    "bytes": 74151
  },
  {
    "id": "btn-ember-frame",
    "pack": "dark-ember",
    "name": "Ember Button (Empty)",
    "category": "button",
    "tags": [
      "button",
      "frame",
      "outline",
      "ghost",
      "secondary"
    ],
    "file": "dark-ember/btn-ember-frame.png",
    "thumb": "dark-ember/thumb/btn-ember-frame.webp",
    "width": 512,
    "height": 256,
    "slice": [
      44,
      50,
      44,
      50
    ],
    "bytes": 8069
  },
  {
    "id": "btn-ember-round",
    "pack": "dark-ember",
    "name": "Ember Round Button",
    "category": "button",
    "tags": [
      "button",
      "round",
      "circle",
      "icon-button"
    ],
    "file": "dark-ember/btn-ember-round.png",
    "thumb": "dark-ember/thumb/btn-ember-round.webp",
    "width": 128,
    "height": 128,
    "slice": null,
    "bytes": 10259
  },
  {
    "id": "btn-ember-square",
    "pack": "dark-ember",
    "name": "Ember Square Button",
    "category": "button",
    "tags": [
      "button",
      "square",
      "red",
      "icon-button"
    ],
    "file": "dark-ember/btn-ember-square.png",
    "thumb": "dark-ember/thumb/btn-ember-square.webp",
    "width": 256,
    "height": 256,
    "slice": [
      44,
      44,
      44,
      44
    ],
    "bytes": 15003
  },
  {
    "id": "btn-ember-square-off",
    "pack": "dark-ember",
    "name": "Ember Square (Idle)",
    "category": "button",
    "tags": [
      "button",
      "square",
      "idle",
      "state"
    ],
    "file": "dark-ember/btn-ember-square-off.png",
    "thumb": "dark-ember/thumb/btn-ember-square-off.webp",
    "width": 256,
    "height": 256,
    "slice": [
      48,
      48,
      48,
      48
    ],
    "bytes": 15819
  },
  {
    "id": "btn-ember-square-on",
    "pack": "dark-ember",
    "name": "Ember Square (Active)",
    "category": "button",
    "tags": [
      "button",
      "square",
      "active",
      "state"
    ],
    "file": "dark-ember/btn-ember-square-on.png",
    "thumb": "dark-ember/thumb/btn-ember-square-on.webp",
    "width": 256,
    "height": 256,
    "slice": [
      48,
      48,
      48,
      48
    ],
    "bytes": 16078
  },
  {
    "id": "btn-ember-wide",
    "pack": "dark-ember",
    "name": "Ember Button (Wide)",
    "category": "button",
    "tags": [
      "button",
      "red",
      "primary",
      "wide"
    ],
    "file": "dark-ember/btn-ember-wide.png",
    "thumb": "dark-ember/thumb/btn-ember-wide.webp",
    "width": 512,
    "height": 256,
    "slice": [
      46,
      56,
      46,
      56
    ],
    "bytes": 21267
  },
  {
    "id": "btn-ember-wide-off",
    "pack": "dark-ember",
    "name": "Ember Button (Idle)",
    "category": "button",
    "tags": [
      "button",
      "red",
      "idle",
      "state"
    ],
    "file": "dark-ember/btn-ember-wide-off.png",
    "thumb": "dark-ember/thumb/btn-ember-wide-off.webp",
    "width": 512,
    "height": 256,
    "slice": [
      48,
      58,
      48,
      58
    ],
    "bytes": 22518
  },
  {
    "id": "btn-ember-wide-on",
    "pack": "dark-ember",
    "name": "Ember Button (Active)",
    "category": "button",
    "tags": [
      "button",
      "red",
      "active",
      "hover",
      "state"
    ],
    "file": "dark-ember/btn-ember-wide-on.png",
    "thumb": "dark-ember/thumb/btn-ember-wide-on.webp",
    "width": 512,
    "height": 256,
    "slice": [
      48,
      58,
      48,
      58
    ],
    "bytes": 22415
  },
  {
    "id": "frame-round-lg",
    "pack": "dark-ember",
    "name": "Round Frame (Large)",
    "category": "frame",
    "tags": [
      "frame",
      "round",
      "circle",
      "portrait",
      "avatar"
    ],
    "file": "dark-ember/frame-round-lg.png",
    "thumb": "dark-ember/thumb/frame-round-lg.webp",
    "width": 512,
    "height": 512,
    "slice": null,
    "bytes": 29705
  },
  {
    "id": "frame-round-sm",
    "pack": "dark-ember",
    "name": "Round Frame (Small)",
    "category": "frame",
    "tags": [
      "frame",
      "round",
      "circle",
      "skill",
      "ability"
    ],
    "file": "dark-ember/frame-round-sm.png",
    "thumb": "dark-ember/thumb/frame-round-sm.webp",
    "width": 64,
    "height": 64,
    "slice": null,
    "bytes": 2437
  },
  {
    "id": "frame-round-sm-icon",
    "pack": "dark-ember",
    "name": "Round Frame (Sword)",
    "category": "frame",
    "tags": [
      "frame",
      "round",
      "skill",
      "attack",
      "sword"
    ],
    "file": "dark-ember/frame-round-sm-icon.png",
    "thumb": "dark-ember/thumb/frame-round-sm-icon.webp",
    "width": 64,
    "height": 64,
    "slice": null,
    "bytes": 3934
  },
  {
    "id": "frame-round-sm-lit",
    "pack": "dark-ember",
    "name": "Round Frame (Lit)",
    "category": "frame",
    "tags": [
      "frame",
      "round",
      "ready",
      "active",
      "skill"
    ],
    "file": "dark-ember/frame-round-sm-lit.png",
    "thumb": "dark-ember/thumb/frame-round-sm-lit.webp",
    "width": 64,
    "height": 64,
    "slice": null,
    "bytes": 3712
  },
  {
    "id": "frame-sm-bevel",
    "pack": "dark-ember",
    "name": "Small Frame (Bevel)",
    "category": "frame",
    "tags": [
      "frame",
      "border",
      "small",
      "bevel",
      "slot"
    ],
    "file": "dark-ember/frame-sm-bevel.png",
    "thumb": "dark-ember/thumb/frame-sm-bevel.webp",
    "width": 256,
    "height": 256,
    "slice": [
      36,
      36,
      36,
      36
    ],
    "bytes": 8355
  },
  {
    "id": "frame-sm-double",
    "pack": "dark-ember",
    "name": "Small Frame (Double)",
    "category": "frame",
    "tags": [
      "frame",
      "border",
      "small",
      "double",
      "slot"
    ],
    "file": "dark-ember/frame-sm-double.png",
    "thumb": "dark-ember/thumb/frame-sm-double.webp",
    "width": 256,
    "height": 256,
    "slice": [
      36,
      36,
      36,
      36
    ],
    "bytes": 6975
  },
  {
    "id": "frame-sm-thin",
    "pack": "dark-ember",
    "name": "Small Frame (Thin)",
    "category": "frame",
    "tags": [
      "frame",
      "border",
      "small",
      "thin",
      "slot"
    ],
    "file": "dark-ember/frame-sm-thin.png",
    "thumb": "dark-ember/thumb/frame-sm-thin.webp",
    "width": 256,
    "height": 256,
    "slice": [
      26,
      26,
      26,
      26
    ],
    "bytes": 4514
  },
  {
    "id": "frame-tall",
    "pack": "dark-ember",
    "name": "Bronze Frame (Tall)",
    "category": "frame",
    "tags": [
      "frame",
      "border",
      "bronze",
      "tall",
      "deco"
    ],
    "file": "dark-ember/frame-tall.png",
    "thumb": "dark-ember/thumb/frame-tall.webp",
    "width": 800,
    "height": 1200,
    "slice": [
      51,
      51,
      51,
      51
    ],
    "bytes": 24240
  },
  {
    "id": "frame-wide",
    "pack": "dark-ember",
    "name": "Bronze Frame (Wide)",
    "category": "frame",
    "tags": [
      "frame",
      "border",
      "bronze",
      "wide",
      "deco"
    ],
    "file": "dark-ember/frame-wide.png",
    "thumb": "dark-ember/thumb/frame-wide.webp",
    "width": 1024,
    "height": 512,
    "slice": [
      50,
      50,
      50,
      50
    ],
    "bytes": 15208
  },
  {
    "id": "frame-wide-alt",
    "pack": "dark-ember",
    "name": "Bronze Frame (Wide II)",
    "category": "frame",
    "tags": [
      "frame",
      "border",
      "bronze",
      "wide",
      "deco"
    ],
    "file": "dark-ember/frame-wide-alt.png",
    "thumb": "dark-ember/thumb/frame-wide-alt.webp",
    "width": 1024,
    "height": 512,
    "slice": [
      50,
      50,
      50,
      50
    ],
    "bytes": 15516
  },
  {
    "id": "icon-armor",
    "pack": "dark-ember",
    "name": "Plate Armor",
    "category": "icon",
    "tags": [
      "icon",
      "armor",
      "chest",
      "equipment",
      "defense"
    ],
    "file": "dark-ember/icon-armor.png",
    "thumb": "dark-ember/thumb/icon-armor.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 33264
  },
  {
    "id": "icon-axe",
    "pack": "dark-ember",
    "name": "Battle Axe",
    "category": "icon",
    "tags": [
      "icon",
      "axe",
      "weapon",
      "equipment",
      "attack"
    ],
    "file": "dark-ember/icon-axe.png",
    "thumb": "dark-ember/thumb/icon-axe.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 17801
  },
  {
    "id": "icon-rune-stone",
    "pack": "dark-ember",
    "name": "Rune Stone",
    "category": "icon",
    "tags": [
      "icon",
      "rune",
      "stone",
      "gem",
      "craft",
      "material"
    ],
    "file": "dark-ember/icon-rune-stone.png",
    "thumb": "dark-ember/thumb/icon-rune-stone.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 18139
  },
  {
    "id": "panel-tall-ornate",
    "pack": "dark-ember",
    "name": "Ornate Panel (Tall)",
    "category": "panel",
    "tags": [
      "panel",
      "window",
      "ornate",
      "tall",
      "sidebar"
    ],
    "file": "dark-ember/panel-tall-ornate.png",
    "thumb": "dark-ember/thumb/panel-tall-ornate.webp",
    "width": 1024,
    "height": 1536,
    "slice": [
      85,
      85,
      85,
      85
    ],
    "bytes": 193969
  },
  {
    "id": "panel-wide-ornate",
    "pack": "dark-ember",
    "name": "Ornate Panel (Wide)",
    "category": "panel",
    "tags": [
      "panel",
      "window",
      "ornate",
      "wide",
      "dialog"
    ],
    "file": "dark-ember/panel-wide-ornate.png",
    "thumb": "dark-ember/thumb/panel-wide-ornate.webp",
    "width": 1024,
    "height": 512,
    "slice": [
      70,
      70,
      70,
      70
    ],
    "bytes": 82711
  },
  {
    "id": "silhouette-warrior-f",
    "pack": "dark-ember",
    "name": "Warrior Silhouette (F)",
    "category": "silhouette",
    "tags": [
      "silhouette",
      "character",
      "warrior",
      "class",
      "select",
      "paperdoll"
    ],
    "file": "dark-ember/silhouette-warrior-f.png",
    "thumb": "dark-ember/thumb/silhouette-warrior-f.webp",
    "width": 700,
    "height": 1400,
    "slice": null,
    "bytes": 75787
  },
  {
    "id": "silhouette-warrior-m",
    "pack": "dark-ember",
    "name": "Warrior Silhouette (M)",
    "category": "silhouette",
    "tags": [
      "silhouette",
      "character",
      "warrior",
      "class",
      "select",
      "paperdoll"
    ],
    "file": "dark-ember/silhouette-warrior-m.png",
    "thumb": "dark-ember/thumb/silhouette-warrior-m.webp",
    "width": 700,
    "height": 1400,
    "slice": null,
    "bytes": 99214
  },
  {
    "id": "skill-comet",
    "pack": "dark-ember",
    "name": "Comet Slash",
    "category": "icon",
    "tags": [
      "skill",
      "spell",
      "comet",
      "slash",
      "ability",
      "cutout"
    ],
    "file": "dark-ember/skill-comet.png",
    "thumb": "dark-ember/thumb/skill-comet.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 26446
  },
  {
    "id": "skill-comet-sq",
    "pack": "dark-ember",
    "name": "Comet Slash (Framed)",
    "category": "icon",
    "tags": [
      "skill",
      "spell",
      "comet",
      "slash",
      "ability",
      "framed"
    ],
    "file": "dark-ember/skill-comet-sq.png",
    "thumb": "dark-ember/thumb/skill-comet-sq.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 28925
  },
  {
    "id": "skill-firehand",
    "pack": "dark-ember",
    "name": "Firehand",
    "category": "icon",
    "tags": [
      "skill",
      "spell",
      "fire",
      "ability",
      "cutout"
    ],
    "file": "dark-ember/skill-firehand.png",
    "thumb": "dark-ember/thumb/skill-firehand.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 27843
  },
  {
    "id": "skill-firehand-sq",
    "pack": "dark-ember",
    "name": "Firehand (Framed)",
    "category": "icon",
    "tags": [
      "skill",
      "spell",
      "fire",
      "ability",
      "framed"
    ],
    "file": "dark-ember/skill-firehand-sq.png",
    "thumb": "dark-ember/thumb/skill-firehand-sq.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 29294
  },
  {
    "id": "skill-soulskull",
    "pack": "dark-ember",
    "name": "Soul Skull",
    "category": "icon",
    "tags": [
      "skill",
      "spell",
      "shadow",
      "skull",
      "curse",
      "cutout"
    ],
    "file": "dark-ember/skill-soulskull.png",
    "thumb": "dark-ember/thumb/skill-soulskull.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 33382
  },
  {
    "id": "skill-soulskull-sq",
    "pack": "dark-ember",
    "name": "Soul Skull (Framed)",
    "category": "icon",
    "tags": [
      "skill",
      "spell",
      "shadow",
      "skull",
      "curse",
      "framed"
    ],
    "file": "dark-ember/skill-soulskull-sq.png",
    "thumb": "dark-ember/thumb/skill-soulskull-sq.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 34274
  },
  {
    "id": "skill-thunderhammer",
    "pack": "dark-ember",
    "name": "Thunder Hammer",
    "category": "icon",
    "tags": [
      "skill",
      "spell",
      "lightning",
      "hammer",
      "holy",
      "cutout"
    ],
    "file": "dark-ember/skill-thunderhammer.png",
    "thumb": "dark-ember/thumb/skill-thunderhammer.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 28332
  },
  {
    "id": "skill-thunderhammer-sq",
    "pack": "dark-ember",
    "name": "Thunder Hammer (Framed)",
    "category": "icon",
    "tags": [
      "skill",
      "spell",
      "lightning",
      "hammer",
      "holy",
      "framed"
    ],
    "file": "dark-ember/skill-thunderhammer-sq.png",
    "thumb": "dark-ember/thumb/skill-thunderhammer-sq.webp",
    "width": 256,
    "height": 256,
    "slice": null,
    "bytes": 30172
  },
  {
    "id": "bar-fill-health",
    "pack": "stone-vine",
    "name": "Health Fill (Green)",
    "category": "bar",
    "tags": [
      "bar",
      "fill",
      "health",
      "hp",
      "green"
    ],
    "file": "stone-vine/bar-fill-health.png",
    "thumb": "stone-vine/thumb/bar-fill-health.webp",
    "width": 532,
    "height": 56,
    "slice": [
      0,
      28,
      0,
      28
    ],
    "bytes": 10106
  },
  {
    "id": "bar-fill-mana",
    "pack": "stone-vine",
    "name": "Mana Fill (Arcane)",
    "category": "bar",
    "tags": [
      "bar",
      "fill",
      "mana",
      "mp",
      "blue",
      "purple"
    ],
    "file": "stone-vine/bar-fill-mana.png",
    "thumb": "stone-vine/thumb/bar-fill-mana.webp",
    "width": 536,
    "height": 56,
    "slice": [
      0,
      28,
      0,
      28
    ],
    "bytes": 10705
  },
  {
    "id": "bar-fill-stamina",
    "pack": "stone-vine",
    "name": "Stamina Fill (Gold)",
    "category": "bar",
    "tags": [
      "bar",
      "fill",
      "stamina",
      "xp",
      "gold",
      "yellow"
    ],
    "file": "stone-vine/bar-fill-stamina.png",
    "thumb": "stone-vine/thumb/bar-fill-stamina.webp",
    "width": 533,
    "height": 55,
    "slice": [
      0,
      28,
      0,
      28
    ],
    "bytes": 10588
  },
  {
    "id": "bar-track-stone",
    "pack": "stone-vine",
    "name": "Stone Bar Track",
    "category": "bar",
    "tags": [
      "bar",
      "track",
      "progress",
      "health"
    ],
    "file": "stone-vine/bar-track-stone.png",
    "thumb": "stone-vine/thumb/bar-track-stone.webp",
    "width": 627,
    "height": 103,
    "slice": [
      30,
      62,
      32,
      62
    ],
    "bytes": 40065
  },
  {
    "id": "bar-track-stone-1",
    "pack": "stone-vine",
    "name": "Stone Bar Track II",
    "category": "bar",
    "tags": [
      "bar",
      "track",
      "progress"
    ],
    "file": "stone-vine/bar-track-stone-1.png",
    "thumb": "stone-vine/thumb/bar-track-stone-1.webp",
    "width": 627,
    "height": 103,
    "slice": [
      30,
      62,
      32,
      62
    ],
    "bytes": 40065
  },
  {
    "id": "bar-track-stone-2",
    "pack": "stone-vine",
    "name": "Stone Bar Track III",
    "category": "bar",
    "tags": [
      "bar",
      "track",
      "progress"
    ],
    "file": "stone-vine/bar-track-stone-2.png",
    "thumb": "stone-vine/thumb/bar-track-stone-2.webp",
    "width": 598,
    "height": 103,
    "slice": [
      30,
      58,
      32,
      58
    ],
    "bytes": 29674
  },
  {
    "id": "bar-track-stone-3",
    "pack": "stone-vine",
    "name": "Stone Bar Track IV",
    "category": "bar",
    "tags": [
      "bar",
      "track",
      "progress"
    ],
    "file": "stone-vine/bar-track-stone-3.png",
    "thumb": "stone-vine/thumb/bar-track-stone-3.webp",
    "width": 627,
    "height": 103,
    "slice": [
      30,
      62,
      32,
      62
    ],
    "bytes": 40065
  },
  {
    "id": "bg-scene-dark",
    "pack": "stone-vine",
    "name": "Dark Scene Backdrop",
    "category": "background",
    "tags": [
      "background",
      "backdrop",
      "scene",
      "vignette",
      "menu"
    ],
    "file": "stone-vine/bg-scene-dark.png",
    "thumb": "stone-vine/thumb/bg-scene-dark.webp",
    "width": 1920,
    "height": 1047,
    "slice": null,
    "bytes": 1508561
  },
  {
    "id": "btn-icon-back",
    "pack": "stone-vine",
    "name": "Back Button",
    "category": "button",
    "tags": [
      "icon-button",
      "back",
      "navigation",
      "arrow"
    ],
    "file": "stone-vine/btn-icon-back.png",
    "thumb": "stone-vine/thumb/btn-icon-back.webp",
    "width": 186,
    "height": 186,
    "slice": null,
    "bytes": 24300
  },
  {
    "id": "btn-icon-close",
    "pack": "stone-vine",
    "name": "Close Button",
    "category": "button",
    "tags": [
      "icon-button",
      "close",
      "dismiss",
      "x"
    ],
    "file": "stone-vine/btn-icon-close.png",
    "thumb": "stone-vine/thumb/btn-icon-close.webp",
    "width": 182,
    "height": 183,
    "slice": null,
    "bytes": 24632
  },
  {
    "id": "btn-icon-settings",
    "pack": "stone-vine",
    "name": "Settings Button",
    "category": "button",
    "tags": [
      "icon-button",
      "settings",
      "options",
      "gear",
      "cog"
    ],
    "file": "stone-vine/btn-icon-settings.png",
    "thumb": "stone-vine/thumb/btn-icon-settings.webp",
    "width": 177,
    "height": 178,
    "slice": null,
    "bytes": 26732
  },
  {
    "id": "btn-stone-long",
    "pack": "stone-vine",
    "name": "Stone Button (Long)",
    "category": "button",
    "tags": [
      "button",
      "teal",
      "menu",
      "wide"
    ],
    "file": "stone-vine/btn-stone-long.png",
    "thumb": "stone-vine/thumb/btn-stone-long.webp",
    "width": 674,
    "height": 176,
    "slice": [
      48,
      64,
      52,
      64
    ],
    "bytes": 84262
  },
  {
    "id": "btn-stone-med",
    "pack": "stone-vine",
    "name": "Stone Button (Medium)",
    "category": "button",
    "tags": [
      "button",
      "teal",
      "compact"
    ],
    "file": "stone-vine/btn-stone-med.png",
    "thumb": "stone-vine/thumb/btn-stone-med.webp",
    "width": 272,
    "height": 150,
    "slice": [
      42,
      56,
      46,
      56
    ],
    "bytes": 32517
  },
  {
    "id": "btn-stone-wide",
    "pack": "stone-vine",
    "name": "Stone Button (Wide)",
    "category": "button",
    "tags": [
      "button",
      "teal",
      "primary"
    ],
    "file": "stone-vine/btn-stone-wide.png",
    "thumb": "stone-vine/thumb/btn-stone-wide.webp",
    "width": 461,
    "height": 151,
    "slice": [
      42,
      58,
      46,
      58
    ],
    "bytes": 52582
  },
  {
    "id": "divider-vine",
    "pack": "stone-vine",
    "name": "Vine Divider",
    "category": "decor",
    "tags": [
      "divider",
      "separator",
      "rule",
      "vine",
      "ornament"
    ],
    "file": "stone-vine/divider-vine.png",
    "thumb": "stone-vine/thumb/divider-vine.webp",
    "width": 904,
    "height": 190,
    "slice": [
      0,
      200,
      0,
      200
    ],
    "bytes": 80272
  },
  {
    "id": "icon-chest",
    "pack": "stone-vine",
    "name": "Treasure Chest",
    "category": "icon",
    "tags": [
      "icon",
      "chest",
      "loot",
      "reward",
      "treasure"
    ],
    "file": "stone-vine/icon-chest.png",
    "thumb": "stone-vine/thumb/icon-chest.webp",
    "width": 152,
    "height": 150,
    "slice": null,
    "bytes": 16637
  },
  {
    "id": "icon-coins",
    "pack": "stone-vine",
    "name": "Gold Coins",
    "category": "icon",
    "tags": [
      "icon",
      "coins",
      "gold",
      "currency",
      "money"
    ],
    "file": "stone-vine/icon-coins.png",
    "thumb": "stone-vine/thumb/icon-coins.webp",
    "width": 148,
    "height": 156,
    "slice": null,
    "bytes": 15236
  },
  {
    "id": "icon-heart",
    "pack": "stone-vine",
    "name": "Heart",
    "category": "icon",
    "tags": [
      "icon",
      "heart",
      "health",
      "life",
      "hp"
    ],
    "file": "stone-vine/icon-heart.png",
    "thumb": "stone-vine/thumb/icon-heart.webp",
    "width": 168,
    "height": 156,
    "slice": null,
    "bytes": 13334
  },
  {
    "id": "icon-key",
    "pack": "stone-vine",
    "name": "Brass Key",
    "category": "icon",
    "tags": [
      "icon",
      "key",
      "unlock",
      "quest"
    ],
    "file": "stone-vine/icon-key.png",
    "thumb": "stone-vine/thumb/icon-key.webp",
    "width": 101,
    "height": 161,
    "slice": null,
    "bytes": 7499
  },
  {
    "id": "icon-potion",
    "pack": "stone-vine",
    "name": "Potion Flask",
    "category": "icon",
    "tags": [
      "icon",
      "potion",
      "flask",
      "consumable",
      "elixir"
    ],
    "file": "stone-vine/icon-potion.png",
    "thumb": "stone-vine/thumb/icon-potion.webp",
    "width": 107,
    "height": 170,
    "slice": null,
    "bytes": 10150
  },
  {
    "id": "icon-sack",
    "pack": "stone-vine",
    "name": "Coin Sack",
    "category": "icon",
    "tags": [
      "icon",
      "sack",
      "bag",
      "loot",
      "currency"
    ],
    "file": "stone-vine/icon-sack.png",
    "thumb": "stone-vine/thumb/icon-sack.webp",
    "width": 147,
    "height": 172,
    "slice": null,
    "bytes": 17393
  },
  {
    "id": "icon-scroll",
    "pack": "stone-vine",
    "name": "Map Scroll",
    "category": "icon",
    "tags": [
      "icon",
      "scroll",
      "map",
      "quest",
      "papyrus",
      "lore"
    ],
    "file": "stone-vine/icon-scroll.png",
    "thumb": "stone-vine/thumb/icon-scroll.webp",
    "width": 191,
    "height": 185,
    "slice": null,
    "bytes": 16912
  },
  {
    "id": "icon-shield",
    "pack": "stone-vine",
    "name": "Wooden Shield",
    "category": "icon",
    "tags": [
      "icon",
      "shield",
      "defense",
      "armor",
      "block"
    ],
    "file": "stone-vine/icon-shield.png",
    "thumb": "stone-vine/thumb/icon-shield.webp",
    "width": 137,
    "height": 172,
    "slice": null,
    "bytes": 15570
  },
  {
    "id": "icon-star",
    "pack": "stone-vine",
    "name": "Gold Star",
    "category": "icon",
    "tags": [
      "icon",
      "star",
      "rating",
      "favourite",
      "reward"
    ],
    "file": "stone-vine/icon-star.png",
    "thumb": "stone-vine/thumb/icon-star.webp",
    "width": 138,
    "height": 156,
    "slice": null,
    "bytes": 7111
  },
  {
    "id": "icon-sword",
    "pack": "stone-vine",
    "name": "Iron Sword",
    "category": "icon",
    "tags": [
      "icon",
      "sword",
      "weapon",
      "attack",
      "melee"
    ],
    "file": "stone-vine/icon-sword.png",
    "thumb": "stone-vine/thumb/icon-sword.webp",
    "width": 142,
    "height": 184,
    "slice": null,
    "bytes": 9171
  },
  {
    "id": "orb-arcane",
    "pack": "stone-vine",
    "name": "Arcane Orb Vial",
    "category": "decor",
    "tags": [
      "orb",
      "vial",
      "bottle",
      "decor",
      "endcap"
    ],
    "file": "stone-vine/orb-arcane.png",
    "thumb": "stone-vine/thumb/orb-arcane.webp",
    "width": 122,
    "height": 176,
    "slice": null,
    "bytes": 11420
  },
  {
    "id": "panel-arch",
    "pack": "stone-vine",
    "name": "Arched Window Frame",
    "category": "panel",
    "tags": [
      "window",
      "arch",
      "ornate",
      "dialog",
      "frame"
    ],
    "file": "stone-vine/panel-arch.png",
    "thumb": "stone-vine/thumb/panel-arch.webp",
    "width": 804,
    "height": 804,
    "slice": [
      150,
      80,
      110,
      80
    ],
    "bytes": 137510
  },
  {
    "id": "panel-arch-fill",
    "pack": "stone-vine",
    "name": "Arched Window Fill",
    "category": "panel",
    "tags": [
      "window",
      "fill",
      "slate",
      "background"
    ],
    "file": "stone-vine/panel-arch-fill.png",
    "thumb": "stone-vine/thumb/panel-arch-fill.webp",
    "width": 686,
    "height": 744,
    "slice": [
      60,
      60,
      60,
      60
    ],
    "bytes": 321935
  },
  {
    "id": "panel-stone",
    "pack": "stone-vine",
    "name": "Stone Window Frame",
    "category": "panel",
    "tags": [
      "window",
      "dialog",
      "modal",
      "stone",
      "frame"
    ],
    "file": "stone-vine/panel-stone.png",
    "thumb": "stone-vine/thumb/panel-stone.webp",
    "width": 747,
    "height": 642,
    "slice": [
      96,
      96,
      96,
      96
    ],
    "bytes": 91714
  },
  {
    "id": "panel-stone-fill",
    "pack": "stone-vine",
    "name": "Stone Window Fill",
    "category": "panel",
    "tags": [
      "window",
      "fill",
      "slate",
      "background"
    ],
    "file": "stone-vine/panel-stone-fill.png",
    "thumb": "stone-vine/thumb/panel-stone-fill.webp",
    "width": 683,
    "height": 574,
    "slice": [
      60,
      60,
      60,
      60
    ],
    "bytes": 253317
  },
  {
    "id": "slot-stone-lg",
    "pack": "stone-vine",
    "name": "Inventory Slot L (Frame)",
    "category": "slot",
    "tags": [
      "inventory",
      "slot",
      "large",
      "vine"
    ],
    "file": "stone-vine/slot-stone-lg.png",
    "thumb": "stone-vine/thumb/slot-stone-lg.webp",
    "width": 274,
    "height": 296,
    "slice": [
      46,
      46,
      46,
      46
    ],
    "bytes": 18995
  },
  {
    "id": "slot-stone-lg-fill",
    "pack": "stone-vine",
    "name": "Inventory Slot L (Fill)",
    "category": "slot",
    "tags": [
      "inventory",
      "slot",
      "fill"
    ],
    "file": "stone-vine/slot-stone-lg-fill.png",
    "thumb": "stone-vine/thumb/slot-stone-lg-fill.webp",
    "width": 271,
    "height": 294,
    "slice": [
      40,
      40,
      40,
      40
    ],
    "bytes": 54325
  },
  {
    "id": "slot-stone-long",
    "pack": "stone-vine",
    "name": "Long Slot / Input Track",
    "category": "slot",
    "tags": [
      "slot",
      "input",
      "field",
      "row",
      "track"
    ],
    "file": "stone-vine/slot-stone-long.png",
    "thumb": "stone-vine/thumb/slot-stone-long.webp",
    "width": 733,
    "height": 124,
    "slice": [
      40,
      54,
      42,
      54
    ],
    "bytes": 50301
  },
  {
    "id": "slot-stone-md",
    "pack": "stone-vine",
    "name": "Inventory Slot M (Frame)",
    "category": "slot",
    "tags": [
      "inventory",
      "slot",
      "medium",
      "vine"
    ],
    "file": "stone-vine/slot-stone-md.png",
    "thumb": "stone-vine/thumb/slot-stone-md.webp",
    "width": 229,
    "height": 235,
    "slice": [
      40,
      40,
      40,
      40
    ],
    "bytes": 17812
  },
  {
    "id": "slot-stone-md-fill",
    "pack": "stone-vine",
    "name": "Inventory Slot M (Fill)",
    "category": "slot",
    "tags": [
      "inventory",
      "slot",
      "fill"
    ],
    "file": "stone-vine/slot-stone-md-fill.png",
    "thumb": "stone-vine/thumb/slot-stone-md-fill.webp",
    "width": 188,
    "height": 199,
    "slice": [
      30,
      30,
      30,
      30
    ],
    "bytes": 35628
  },
  {
    "id": "slot-stone-sm",
    "pack": "stone-vine",
    "name": "Inventory Slot S (Frame)",
    "category": "slot",
    "tags": [
      "inventory",
      "slot",
      "small"
    ],
    "file": "stone-vine/slot-stone-sm.png",
    "thumb": "stone-vine/thumb/slot-stone-sm.webp",
    "width": 188,
    "height": 198,
    "slice": [
      34,
      34,
      34,
      34
    ],
    "bytes": 12628
  },
  {
    "id": "slot-stone-sm-fill",
    "pack": "stone-vine",
    "name": "Inventory Slot S (Fill)",
    "category": "slot",
    "tags": [
      "inventory",
      "slot",
      "fill"
    ],
    "file": "stone-vine/slot-stone-sm-fill.png",
    "thumb": "stone-vine/thumb/slot-stone-sm-fill.webp",
    "width": 153,
    "height": 163,
    "slice": [
      26,
      26,
      26,
      26
    ],
    "bytes": 23980
  }
];

export const ASSETS_BY_ID: Record<string, AssetRecord> = Object.fromEntries(
  ASSETS.map((a) => [a.id, a]),
);
